version: "3.8"

services:
  postgresdb:
    image: postgres:16.2-alpine3.19
    restart: always
    environment:
      POSTGRES_USER: bughounduser
      POSTGRES_PASSWORD: bughound123
      POSTGRES_DB: bughound
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
      # Uncomment the following line if you want to provide dummy data for testing purposes
      # - ./SampleQuery.sql:/docker-entrypoint-initdb.d/SampleQuery.sql 

  backend:
    depends_on:
      - postgresdb
    build: ./bughound_backend/bughound
    restart: always
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresdb:5432/bughound
      SPRING_DATASOURCE_USERNAME: bughounduser
      SPRING_DATASOURCE_PASSWORD: bughound123
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      
  frontend:
    depends_on:
      - backend
    build: ./bughound_frontend
    restart: always
    ports:
      - 5173:80

volumes:
  pgdata:
